name: datacollection_example
description: A new Flutter package project.
version: 0.0.1
homepage: none

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  datacollection: 
    path : ./../annotation
  json_annotation: ^4.8.0
  logger: ^1.0.0
  dio: ^5.3.2
  retrofit: ^4.0.1

dev_dependencies: 
  build_runner: ^2.1.7
  source_gen_test: ^1.0.2
  test: ^1.20.1
  json_serializable: ^6.1.3
  datacollection_generator: 
    path : ./../generator
  http_mock_adapter: ^0.4.4
  retrofit_generator: 
    path : ./../../../mylekha_helper/retrofit.dart/generator

dependency_overrides:
  datacollection:
    path: ../annotation
  datacollection_generator:
    path: ../generator
  source_gen: ^1.0.0