name: datacollection_example
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  datacollection:
  json_annotation:
  logger: ^1.0.0
  dio: ^4.0.0

dev_dependencies: 
  source_gen_test: ^1.0.2
  test: ^1.20.1

dependency_overrides:
  datacollection:
    path: ../annotation
  datacollection_generator:
    path: ../generator
  source_gen: ^1.0.0