name: datacollection_generator
description: datacollection generator
version: 0.0.2+1
homepage: https://github.com/kechankrisna/datacollection

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  build: ^2.0.1
  source_gen: ^1.0.1
  datacollection: ^0.0.2
  dio: ^4.0.1
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  analyzer: ^3.0.0
  dart_style: ^2.0.1
  json_annotation: ^4.4.0

dev_dependencies: 
  build_runner: ^2.1.7
  build_test: ^2.1.5
  source_gen_test: ^1.0.2
  test: ^1.20.1
  json_serializable: ^6.1.3

dependency_overrides:
  datacollection: 
    path: ../annotation

