name: datacollection_generator
description: datacollection generator
version: 0.0.3+5
homepage: https://github.com/kechankrisna/datacollection

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  build: ^2.3.0 ## active
  source_gen: ^1.0.1 ## active
  datacollection: 
    path: ../annotation
  dio: ^5.3.2 ## active
  built_collection: ^5.0.0 ## inactive (google.dev)
  code_builder: ^4.5.0 ## active (tools.google.dev)
  tuple: ^2.0.2 ## active (google.dev)
  analyzer: ^6.0.0 ## active (tools.google.dev)
  dart_style: ^2.3.2 ## active (tools.google.dev)
  json_annotation: ^4.8.1 ## active (google.dev)

dev_dependencies: 
  build_runner: ^2.4.6 ## active (tools.google.dev)
  build_test: ^2.2.0 ## active (tools.google.dev)
  source_gen_test: ^1.0.6 ## active
  test: ^1.24.6 ## active (dart.dev)
  json_serializable: ^6.6.2 ## active (goole.dev)

