name: datacollection_generator
description: datacollection generator
version: 0.0.3+5
homepage: https://github.com/kechankrisna/datacollection

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.0.1
  # datacollection: ^0.0.3+6
  dio: ^5.3.2
  built_collection: ^5.0.0
  code_builder: ^4.5.0
  tuple: ^2.0.2
  analyzer: ^6.0.0
  dart_style: ^2.3.2
  json_annotation: ^4.8.1

dev_dependencies: 
  build_runner: ^2.4.6
  build_test: ^2.2.0
  source_gen_test: ^1.0.6
  test: ^1.24.6
  json_serializable: ^6.7.1

# dependency_overrides:
  datacollection: 
    path: ../annotation

