name: datacollection_generator
description: datacollection generator
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^4.0.1
  source_gen: ^1.0.1
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  analyzer: ^3.0.0
  dart_style: ^2.0.1
  build: ^2.0.1
  datacollection: 
    path: ../annotation

dev_dependencies: 
  source_gen_test: ^1.0.2
  test: ^1.20.1

