name: datacollection

ide:
  intellij: true

packages:
  - /**

scripts:
  analyze: 
    run: melos exec -- "dart analyze . --fail-fast"
  
  test: 
    run: melos run test:dart --no-select
    description: Run Dart tests for a specific package in this project.

  test:dart:
    run: melos exec  -c 1 --fail-fast -- "\$MELOS_ROOT_PATH/scripts/coverage.sh"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test