name: datacollection
description: this will help to generate the data collection in *.g.dart file from api response
version: 0.0.3+6
homepage: https://github.com/kechankrisna/datacollection

environment:
 sdk: '>=2.18.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  dio: ^5.3.2
  meta: ^1.9.1
dev_dependencies: 
  test: ^1.21.4
  