name: datacollection
description: this will help to generate the data collection in *.g.dart file from api response
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  dio: ^4.0.1
  meta: ^1.3.0
  