name: datacollection
description: this will help to generate the data collection in *.g.dart file from api response
version: 0.0.3+1
homepage: https://github.com/kechankrisna/datacollection

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  collection: ^1.16.0
  dio: ^4.0.5
  meta: ^1.7.0
dev_dependencies: 
  test: ^1.21.4
  