name: datacollection
description: this will help to generate the data collection in *.g.dart file from api response
version: 0.0.2
homepage: https://github.com/kechankrisna/datacollection

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  collection: ^1.15.0
  dio: ^4.0.1
  meta: ^1.3.0
  