name: datacollection
description: this will help to generate the data collection in *.g.dart file from api response
version: 0.0.3+6
homepage: https://github.com/kechankrisna/datacollection

environment:
 sdk: '>=2.19.0 <4.0.0'

dependencies:
  collection: ^1.17.1 ## active (dart.dev)
  dio: ^5.3.2 ## active
  meta: ^1.9.1 ## active (dart.dev)
dev_dependencies: 
  test: ^1.24.4 ## active
  